### ISSUE TITLE
Testing out github task lists

### ISSUE THREAD

**Issue by danieltott** [Virtual-Coffee/virtualcoffee.io#1118]
https://docs.github.com/en/issues/managing-your-tasks-with-tasklists/creating-a-tasklist

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
- [ ] Dang you can edit it in markdown
- [ ] https://github.com/Virtual-Coffee/virtualcoffee.io/issues/1117
- [ ] https://github.com/Virtual-Coffee/virtualcoffee.io/issues/1119
```

**Comment by danieltott** [comment]
Here's the markdown currently: 

````
https://docs.github.com/en/issues/managing-your-tasks-with-tasklists/creating-a-tasklist

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
- [ ] Dang you can edit it in markdown
- [ ] https://github.com/Virtual-Coffee/virtualcoffee.io/issues/1117
- [ ] https://github.com/Virtual-Coffee/virtualcoffee.io/issues/1119
```
````

**Comment by meg-gutshall** [comment]
<img src="https://media3.giphy.com/media/r1HGFou3mUwMw/giphy-downsized-medium.gif"/>
